version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: postgres-blog
    environment:
      POSTGRES_USER: bloguser
      POSTGRES_PASSWORD: blogpassword
      POSTGRES_DB: blogdb
    ports:
      - "5432:5432"
